apiVersion: v1
kind: Service
metadata:
  name: banking-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/api/auth/login"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8076"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "3"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
spec:
  type: LoadBalancer
  selector:
    app: banking-app
  ports:
    - port: 80
      targetPort: 8076
      nodePort: 30964