apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app-deployment
  labels:
    app: banking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-app
  template:
    metadata:
      labels:
        app: banking-app
    spec:
      containers:
        - name: banking-app
          image: ziazeshan141/fintech-banking-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8076
          env:
            - name: SERVER_ADDRESS
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: "8076"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/Fintech_Finance_Database?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password123"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: "org.hibernate.dialect.MySQL8Dialect"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"