apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app-deployment
  labels:
    app: banking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-app
  template:
    metadata:
      labels:
        app: banking-app
    spec:
      containers:
        - name: banking-app
          image: ziazeshan141/fintech-banking-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8076
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/bank_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
         
---
apiVersion: v1
kind: Service
metadata:
  name: banking-app-service
spec:
  type: LoadBalancer # Use NodePort for local clusters like Minikube
  selector:
    app: banking-app
  ports:
    - port: 80
      targetPort: 8076