apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "password123"
  MYSQL_DATABASE: "Fintech_Finance_Database"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "password123"